#!/usr/bin/env bash
# Which statement is correct for the TCP box:
# Which statement is correct for the UDP box:
# Which statement is correct for the TCP worker:

1 # It is a protocol that is transferring data in a slow way but surely
2 # It is a protocol that is transferring data in a fast way and might loss data along in the process
1 # Have you received boxes x, y, z?
